### ISSUE TITLE
install blobfuse on Ubuntu 18.04

### ISSUE THREAD

**Issue by JWDobken** [Azure/azure-storage-fuse#190]
Now the Ubuntu 18.04 is available on Azure, I would like  to install blobfuse here.

    wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
    sudo dpkg -i packages-microsoft-prod.deb
    sudo apt-get update
    sudo apt-get install blobfuse

But it returns:

    Reading package lists... Done
    Building dependency tree
    Reading state information... Done
    E: Unable to locate package blobfuse

**Comment by ysayesso** [comment]
Same as for me here. It will be better to get this fixed soon.

**Comment by seguler** [comment]
How do you install the 18.10 version on Azure ? When I create an Ubuntu, I only see 14.04, 16.04 and 17.10 releases.

**Comment by seguler** [comment]
Ok - found it through the search.

We just published the package for 18.10 as well. Please let me know if you encounter any issues with it.

**Comment by JWDobken** [comment]
I think you mean 18.04 since 18.10 is not yet released?

**Comment by ysayesso** [comment]
I still can t install blobfuse for ubuntu 18.04, I get the same error as for @JWDobken

**Comment by seguler** [comment]
My bad - for some reason I created a binary for 18.10 :) Hoping to fix this today

**Comment by ysayesso** [comment]
I created a new Ubuntu 18.04 LTS and then installed the blobfuse, it works fine. But if I try to install Blobfuse on my old Ubuntu 18.04 LTS vm where I really want the blobfuse to be installed, it doesn't  work.. I m still getting the same error as before.

**Comment by seguler** [comment]
I think there is some caching issue on your original 18.04. You need to update your repository cache.. Could be either `sudo apt-get clean` or `sudo apt-get update`

**Comment by ysayesso** [comment]
Thank you! I will try to fix it.

**Comment by JWDobken** [comment]
Confirmed by me that it works on 18.04 LTS
