### ISSUE TITLE
Japanese / Chinese / EU characters in file names

### ISSUE THREAD

**Issue by chanaka-jostle** [Azure/azure-storage-fuse#52]
Hello,

I am getting permission denied errors trying to copy files with Japanese, Chinese, EU characters using this azure-storage-fuse . If I upload those files manually to the blob storage in Azure they are accepted no problem. I can copy files without these characters fine with azure-storage-fuse . Do I have a configuration problem or is this a bug? Also Azure blob storage allows file names that are longer than 255 characters. azure-storage-fuse seems to be limited to 255 characters.

Thanks

**Comment by seguler** [comment]
Thanks for reporting. I believe this is a bug - which we should fix in the next release

**Comment by chanaka-jostle** [comment]
Thanks! Will you also increase the filename length limit?

Chanaka

**Comment by chanaka-jostle** [comment]
Hello,

Here are some file names I was testing with. These file names work with
S3FS so I would assume it should be able to with your product also.

117.25.149.175:630Y-Z-DVD周深周深&郭沁-大鱼(国.jpg
🔯 🕎 ☯️ ☦️ 🛐 ⛎ ♈️ ♉️ ♊️ ♋️ ♌️ ♍️ ♎️ ♏️ ♐️ ♑️ ♒️ ♓️ 🆔 ⚛️.png
“ğ,i,ö,ç,ü”.jpg
こんにちは.jpg
批量下载】パノプティコン労働歌 第一等.zip
😀 😁 😂 🤣 😃 😄 😅 😆 😉 😊 😋.zip

Thanks

**Comment by seguler** [comment]
I believe the file name limit of 255 comes from Linux. Paths can be longer but file names need to be shorter than 255 characters.

Are you able to create a file longer than 255 characters in the Linux file system ?

**Comment by chanaka-jostle** [comment]
Hello,

No, I can only create a file name max 255 character. Do you know when you
will have a release for the character fix? I look forward to using this
product.

Thanks
Chanaka

**Comment by chanaka-jostle** [comment]
Hello Seguler,

Azure blob storage can support file names of 1,024 characters long. Even though Linux may support 255 characters file names only, can you remove the 255 character limit in the code because for example I would want transfer a file with a name greater than 255 characters from another file system (S3FS) to azure-storage-fuse directly.

**Comment by seguler** [comment]
Ok - we'll look into this. Could you raise a separate issue for the file name length ?

**Comment by seguler** [comment]
@chanaka-jostle This is now fixed in PR #63 - can you pull from the PR and test it for us ?

My tests all passed with Turkish characters,

**Comment by seguler** [comment]
This is not released in blobfuse 0.2.4

**Comment by chanaka-jostle** [comment]
Hello Sercan,

Sorry, I won't be able to test for a while.

**Comment by XUWeijiang** [comment]
I know this is an old bug, but it looks the bug is still not fixed. I got the same issue using blobfuse 1.2.4.  Please take a look.

**Comment by amnguye** [comment]
@NaraVen @vibhansa-msft Could someone take a look? It might be a bug in the cpplite code or blobfuse code with not encoding correctly.
@XUWeijiang what's the error you get when attempting to upload a file with japanese/chinese/eu characters? If you could provide a sample name of what you're trying to upload, that would be great.

**Comment by NaraVen** [comment]
We have fixed this in our latest source code. Just not released it yet as we are beta testing some ADLS features. You ca wait for the release or take the latest source code.

**Comment by potapuff** [comment]
> We have fixed this in our latest source code. Just not released it yet as we are beta testing some ADLS features. You ca wait for the release or take the latest source code.
@NaraVen can you provide link to commit with fix for #52 ? I'm extremely need for this feature.

**Comment by NaraVen** [comment]
This is the commit that has the fix: https://github.com/Azure/azure-storage-fuse/commit/730374fceae722690722361b12394feb9a083643.
The corresponding blobfuse version is 1.3.1-beta

**Comment by potapuff** [comment]
confirm: 1.3.1-beta work well for cryrilic (russian, ukrainian), and for spaces in name
